### PR TITLE
html file for class meeting status update

### PR DESCRIPTION
**Pull request by skinamangit**
This is the file that was supposed to be created for the Sept. 29 meeting.  Sorry it's late.  I hope this works!

### CODE REVIEW

**Comment by skinamangit** [comment]
I think I closed the pull request by mistake, hope I am re-opening it now.

**Comment by SLAScodes** [comment]
So are you trying to commit to YOUR branch of the class repo? Looks like you got files from the class MASTER branch, altered them, and now you're trying to put them on your branch. Did I get that right?

**Comment by SLAScodes** [comment]
Redo the pull request and do it to YOUR branch of the repo.

**Comment by skinamangit** [comment]
It should be there now, I hopesk

**Comment by SLAScodes** [comment]
Your submission is still earmarked to go to the master branch instead of your branch of the class repo. Please fix and redo the request.

**Pull request closed without merging**
